# Generated by Django 5.0.1 on 2024-01-26 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_url', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('visibility_stats', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='SearchEngineListing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_desktop_keywords_count', models.IntegerField(default=0)),
                ('google_mobile_keywords_count', models.IntegerField(default=0)),
                ('yahoo_keywords_count', models.IntegerField(default=0)),
                ('bing_keywords_count', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='SERPPosition',
            fields=[
                ('serp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_desktop_current_rank', models.IntegerField(blank=True, null=True)),
                ('google_mobile_current_rank', models.IntegerField(blank=True, null=True)),
                ('yahoo_current_rank', models.IntegerField(blank=True, null=True)),
                ('bing_current_rank', models.IntegerField(blank=True, null=True)),
                ('google_desktop_previous_rank', models.IntegerField(blank=True, null=True)),
                ('google_mobile_previous_rank', models.IntegerField(blank=True, null=True)),
                ('yahoo_previous_rank', models.IntegerField(blank=True, null=True)),
                ('bing_previous_rank', models.IntegerField(blank=True, null=True)),
                ('google_desktop_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('google_mobile_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('yahoo_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('bing_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.keyword')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
    ]
