# Generated by Django 5.0.1 on 2024-01-27 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword_text', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('keywords_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='SearchEngineListing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_desktop_keywords_count', models.IntegerField(default=0)),
                ('google_mobile_keywords_count', models.IntegerField(default=0)),
                ('yahoo_keywords_count', models.IntegerField(default=0)),
                ('bing_keywords_count', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='SERPPosition',
            fields=[
                ('serp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_desktop_current_rank', models.IntegerField(blank=True, null=True)),
                ('google_desktop_previous_rank', models.IntegerField(blank=True, null=True)),
                ('google_desktop_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('google_mobile_current_rank', models.IntegerField(blank=True, null=True)),
                ('google_mobile_previous_rank', models.IntegerField(blank=True, null=True)),
                ('google_mobile_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('yahoo_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('yahoo_previous_rank', models.IntegerField(blank=True, null=True)),
                ('yahoo_current_rank', models.IntegerField(blank=True, null=True)),
                ('bing_previous_rank', models.IntegerField(blank=True, null=True)),
                ('bing_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('bing_current_rank', models.IntegerField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.keyword')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_position_count', models.IntegerField(default=0)),
                ('top_five_positions_count', models.IntegerField(default=0)),
                ('first_page_count', models.IntegerField(default=0)),
                ('first_two_pages_count', models.IntegerField(default=0)),
                ('new_listings_count', models.IntegerField(default=0)),
                ('moved_up_count', models.IntegerField(default=0)),
                ('moved_down_count', models.IntegerField(default=0)),
                ('no_change_count', models.IntegerField(default=0)),
                ('total_positions_gained_lost', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
    ]
