# Generated by Django 5.0.1 on 2024-01-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='created_at',
        ),
    ]
